version: '2'
services:
  client:
    container_name: vanne-client
    image: vanne-client:latest
    restart: always
    networks:
      network:
        ipv4_address: 172.20.128.2

  core:
    container_name: vanne-api
    image: vanne-api:latest
    restart: always
    depends_on:
      - db
      # - redis
    environment:
      - APP_PORT=17001
      - DB_HOST=vanne-db
      - DB_USER=${MONGO_ROOT_USER}
      - DB_PWD=${MONGO_ROOT_PASSWORD}
    networks:
      network:
        ipv4_address: 172.20.128.3
      db_network:

  db:
    container_name: vanne-db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - /home/anclaev/projects/vanne/data/db:/data/db
    restart: always
    networks:
      - db_network

  redis:
    container_name: vanne-redis
    image: redis:latest
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    volumes:
      - /home/anclaev/projects/vanne/data/redis:/data
    restart: always
    networks:
      - db_network

networks:
  network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
  db_network:
    driver: bridge

volumes:
  data: {}
